### ISSUE TITLE
NoClassDefFoundError org.florescu.android.rangeseekbar.R$drawable

### ISSUE THREAD

**Issue by altairmizuchi** [anothem/android-range-seek-bar#51]
Hello. When i start an activity with bar i get this exception below. I tried to compile both version of dependencies: stable and snapshot. No difference. What am i doing wrong?

`Caused by: java.lang.NoClassDefFoundError: org.florescu.android.rangeseekbar.R$drawable
                                                                               at org.florescu.android.rangeseekbar.RangeSeekBar.init(RangeSeekBar.java:171)
                                                                               at org.florescu.android.rangeseekbar.RangeSeekBar.<init>(RangeSeekBar.java:146)
                                                                               at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                               at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:270) 
                                                                               at android.app.Activity.setContentView(Activity.java:1881) 
                                                                               at com.cloverrepublic.ActivitiesUI.Statistic.onCreate(Statistic.java:30) `

**Comment by anothem** [comment]
What's your build.gradle look like?

**Comment by altairmizuchi** [comment]
`apply plugin: 'com.android.application'

android {
    signingConfigs {
        config {
        }
    }
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    defaultConfig {
        applicationId "com.cloverrepublic.jeuler.wingymandroidnative"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
        wingymfull {
            minSdkVersion 15
            applicationId 'com.cloverrepublic.wingym'
            targetSdkVersion 23
            versionCode 8
            versionName '1.0'

            resValue "string", "ApplicationTitle", "WinGym"
            resValue "string", "app_name", "WinGym"
        }
    }
}

repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    maven { url "http://maven.batch.com/release" }
    maven { url "https://jitpack.io" }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.batch.android:batch-sdk:1.5+'
    compile 'com.google.android.gms:play-services:8.3.0'
    compile 'com.google.android.gms:play-services-gcm:8.3.0'
    compile 'com.google.android.gms:play-services-analytics:8.3.0'
    compile "com.google.android.gms:play-services-location:8.3.0"
    compile 'com.google.android.gms:play-services-ads:8.3.0'
    compile 'com.google.android.gms:play-services-identity:8.3.0'
    compile 'com.anjlab.android.iab.v3:library:1.0.+'
    compile 'com.kobakei:ratethisapp:0.0.4'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:support-v13:23.1.1'
    compile files('src/libs/FlurryAnalytics-6.1.0.jar')
    compile 'com.michaelpardo:activeandroid:3.1.0-SNAPSHOT'
    compile 'com.nhaarman.listviewanimations:lib-core:3.1.0@aar'
    compile 'com.nhaarman.listviewanimations:lib-manipulation:3.1.0@aar'
    compile 'com.nhaarman.listviewanimations:lib-core-slh:3.1.0@aar'
    compile 'com.nineoldandroids:library:2.4.0+'
    compile 'com.appyvet:materialrangebar:1.3'
    compile 'com.github.PhilJay:MPAndroidChart:v2.2.2'
}
`

**Comment by altairmizuchi** [comment]
oops. I've already started tests for other implementations. Fixed my previous message

**Comment by altairmizuchi** [comment]
I tried newly created project and it worked.
Could you possible help me to understand problem? I will really appreciate it.

**Comment by kamalsint** [comment]
Am also getting the same error pls tell the solution
