### ISSUE TITLE
java.lang.NoClassDefFoundError: org.florescu.android.rangeseekbar.R$drawable

### ISSUE THREAD

**Issue by kamalsint** [anothem/android-range-seek-bar#63]
I am getting this below error when i add this lib via gradle or if i download the project and add it as module in the project. I want to use this type of seekbar in my project and this is perfect for my job but i am unable to get rid of this error in my project.

 FATAL EXCEPTION: main
                                                                  Process: com.medi.trustmedi, PID: 2280
                                                                  java.lang.NoClassDefFoundError: org.florescu.android.rangeseekbar.R$drawable
                                                                      at org.florescu.android.rangeseekbar.RangeSeekBar.init(RangeSeekBar.java:171)
                                                                      at org.florescu.android.rangeseekbar.RangeSeekBar.<init>(RangeSeekBar.java:141)
                                                                      at com.medi.trustmedi.activity.FilterScreenActivity.onCreate(FilterScreenActivity.java:30)
                                                                      at android.app.Activity.performCreate(Activity.java:5264)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2314)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2402)
                                                                      at android.app.ActivityThread.access$900(ActivityThread.java:151)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1333)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                      at android.os.Looper.loop(Looper.java:193)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5304)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                                      at dalvik.system.NativeStart.main(Native Method)

and this is my build.gradle file:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "xxx.xxx.xxxxx"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0.1"
        multiDexEnabled true
        }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        packagingOptions {
            exclude 'META-INF/DEPENDENCIES'
            exclude 'META-INF/NOTICE'
            exclude 'META-INF/LICENSE'
        }
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }
//    useLibrary 'org.apache.http.legacy'
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'org.apache.httpcomponents:httpclient:4.5.2'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
    compile 'com.android.support:appcompat-v7:23.0.0-alpha1'
    compile 'com.android.support:support-v4:23.0.0-alpha1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.google.android.gms:play-services:8.4.0'
    compile 'org.apache.httpcomponents:httpcore:4.3.2'
    compile 'org.apache.httpcomponents:httpmime:4.3.5'
    compile 'com.oguzdev:CircularFloatingActionMenu:1.0.2'
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.google.android.gms:play-services-ads:8.4.0'
    compile 'com.google.android.gms:play-services-identity:8.4.0'
    compile 'com.google.android.gms:play-services-gcm:8.4.0'
    compile 'com.android.support:cardview-v7:23.0.+'
    compile 'com.android.support:recyclerview-v7:23.0.+'
//    compile 'com.pkmmte.view:circularimageview:1.1'
//    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.wunderlist:sliding-layer:1.2.5'
    compile 'com.google.android.gms:play-services-auth:8.4.0'
    compile 'de.hdodenhof:circleimageview:2.0.0'
    compile 'net.hockeyapp.android:HockeySDK:3.7.2'
    compile 'org.florescu.android.rangeseekbar:rangeseekbar-library:0.3.0'
}

Kindly give me some suggestions on what can be done.

**Comment by anothem** [comment]
Sorry @kamalsint, I can't reproduce this :(

**Comment by baloomba** [comment]
Hi @anothem I have the same issue with a Nexus S emulator on Android 19 (x86 + Google APIs)

**Comment by anothem** [comment]
@baloomba could you show me your gradle file please?

**Comment by baloomba** [comment]
`buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
`

`buildscript {
    dependencies {
        classpath 'io.fabric.tools:gradle:1.21.6'
        classpath 'com.testfairy.plugins.gradle:testfairy:1.12'
    }

    repositories {
        mavenCentral()
        maven { url 'https://maven.fabric.io/public' }
        maven { url 'https://www.testfairy.com/maven' }
    }

}

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'testfairy'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.example"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1025
        versionName "1.0.25"
        ndk {
            abiFilters "armeabi-v7a", "armeabi", "x86"
        }
        multiDexEnabled true
    }

    signingConfigs {
        release {...}
    }

    buildTypes {
        release {
            minifyEnabled false
            zipAlignEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        beta {
            applicationIdSuffix ".beta"
            minifyEnabled false
            zipAlignEnabled true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            versionNameSuffix ".4"
        }
        debug {
            applicationIdSuffix ".debug"
            minifyEnabled false
            zipAlignEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    dataBinding {
        enabled true
    }

    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE-FIREBASE.txt'
        exclude 'META-INF/NOTICE'
    }
}

repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
    maven { url 'https://maven.fabric.io/public' }
}

dependencies {

    // ANDROID
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:cardview-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'
    compile 'com.android.support:recyclerview-v7:23.4.0'

    // GOOGLE
    compile 'com.google.android.gms:play-services-location:9.0.0'

    // RANGESEEKBAR
    compile 'org.florescu.android.rangeseekbar:rangeseekbar-library:0.3.0'
}`

Here it is !

**Comment by anothem** [comment]
Thanks @baloomba. Still can't reproduce this :( I'm thinking it might be related to multiDex but not sure and I can't get it to occur on my end. 

If you use the following instead, does it help? 
compile 'org.florescu.android.rangeseekbar:rangeseekbar-library:0.3.0@aar'

**Comment by herbig** [comment]
A bit late but I ran into this same crash on an old project that was using 0.2.0 and switching to 0.3.0@aar resolved it...
